### ISSUE TITLE
@bower_components namespace failing

### ISSUE THREAD

**Issue by bzmw** [dependencies-io/support#26]
I have about 50 packages that have the @bower_components namespace as I migrated them from bower using the bower-away package as outlined here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/

This command runs successfully on my local so not sure what the issue is.

```
Finding available versions for @bower_components/Placeholders.js
exec npm view @bower_components/Placeholders.js --json { silent: true }
Error: exec: internal error
    at Object.error (/usr/src/app/node_modules/shelljs/src/common.js:110:27)
    at Object._exec (/usr/src/app/node_modules/shelljs/src/exec.js:206:12)
    at Object.exec (/usr/src/app/node_modules/shelljs/src/common.js:335:23)
    at getAvailableVersionsOfDependency (/usr/src/app/build/dependency.js:31:43)
    at /usr/src/app/build/manifest.js:110:84
    at Array.forEach (<anonymous>)
    at /usr/src/app/build/manifest.js:101:46
    at Array.forEach (<anonymous>)
    at Manifest.convertToSchema (/usr/src/app/build/manifest.js:99:49)
    at /usr/src/app/build/collect.js:34:34
```

**Comment by davegaeddert** [comment]
Hey @bzmw -- sorry, this got lost in my GitHub notifications. Are you still having an issue with this? Can you point me to a specific repo? Our environment should be pretty similar to a local one, so if there's an issue, I'd really like to get it figured out. Feel free to use the chat on our site if you want to talk privately. Sorry again, and thanks!

**Comment by davegaeddert** [comment]
I'm going to close this for now. Sorry I didn't get back to you sooner, let me know if you want to reopen it.
